FROM alpine:3.10
RUN mkdir /usr/local/redis
RUN wget -O redis.tar.gz http://download.redis.io/releases/redis-4.0.14.tar.gz
RUN tar xf redis.tar.gz -C /usr/local/redis --strip-components=1
RUN rm -rf redis.tar.gz
RUN apk add git

