version: "3.5"
services:
  web:
    image: aishangwei/asw-js-web-demo:0.1
    networks:
      - js-demo-net
    ports:
      - 3000:3000
    deploy:
      replicas: 3
  db:
    image: aishangwei/asw-js-db-demo:0.1
    networks:
      - pets-net
    volumes:
      - asw-js-db-data:/var/lib/postgresql/data

volumes:
  asw-js-db-data:

networks:
  js-demo-net:
    driver: overlay
