FROM centos

MAINTAINER jack "blog.aishangwei.net"
ENV NGINX_VERSION 1.14.0
ENV OPENSSL_VERSION 1.1.1
ENV PCRE_VERSION 8.42
ENV ZLIB_VERSION 1.2.11
ENV BUILD_ROOT /usr/local/src/nginx

# 为了快速构建，这里没有使用 yum update 命令
#RUN yum -y update \
RUN  yum -y install 











